#!/usr/bin/env bash
set -euo pipefail

export TINYACTION_FASTWAM_ROOT="${TINYACTION_FASTWAM_ROOT:-$HOME/tinyaction_fastwam}"
export FASTWAM_DEPLOY_ROOT="${FASTWAM_DEPLOY_ROOT:-$TINYACTION_FASTWAM_ROOT/fastwam-deploy}"
export FASTWAM_UPSTREAM_DIR="${FASTWAM_UPSTREAM_DIR:-$TINYACTION_FASTWAM_ROOT/FastWAM}"
export FASTWAM_PY_DEPS="${FASTWAM_PY_DEPS:-$TINYACTION_FASTWAM_ROOT/python_deps}"
export FASTWAM_ARTIFACTS_DIR="${FASTWAM_ARTIFACTS_DIR:-$TINYACTION_FASTWAM_ROOT/artifacts}"
export FASTWAM_RELEASE_DIR="${FASTWAM_RELEASE_DIR:-$FASTWAM_ARTIFACTS_DIR/checkpoints/fastwam_release}"

export DIFFSYNTH_MODEL_BASE_PATH="${DIFFSYNTH_MODEL_BASE_PATH:-$FASTWAM_ARTIFACTS_DIR/models}"
export DIFFSYNTH_DOWNLOAD_SOURCE="${DIFFSYNTH_DOWNLOAD_SOURCE:-huggingface}"
export HF_HOME="${HF_HOME:-$TINYACTION_FASTWAM_ROOT/hf_home}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$TINYACTION_FASTWAM_ROOT/cache}"
export TMPDIR="${TMPDIR:-$TINYACTION_FASTWAM_ROOT/tmp}"

mkdir -p "$FASTWAM_ARTIFACTS_DIR" "$DIFFSYNTH_MODEL_BASE_PATH" "$HF_HOME" "$XDG_CACHE_HOME" "$TMPDIR"

export PYTHONPATH="$FASTWAM_DEPLOY_ROOT/src:$FASTWAM_PY_DEPS:$FASTWAM_UPSTREAM_DIR/src:$FASTWAM_UPSTREAM_DIR${PYTHONPATH:+:$PYTHONPATH}"
